import ElementsbarLeft from "@/components/ElementsbarLeft";
import ElementsbarRight from "@/components/ElementsbarRight";
import SearchBtn from "@/components/FloatElements/SearchBtn";
import Footer from "@/components/Footer";
import HamburgerNav from "@/components/HamburgerNav";
import Header from "@/components/Header";
import Notification from "@/components/Notification";
import SearchPopup from "@/components/SearchPopup";
import Layout from "@/components/hocs/Layout";
import { Html, Head, Main, NextScript } from "next/document";
import { useState } from "react";
// dark-scheme
export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Header />
        <HamburgerNav />
        <SearchPopup />
        <Main />
        <NextScript />
        <Footer />
        {/*

        <Notification />
*/}
        <SearchBtn />
      </Layout>
    </Html>
  );
}
