import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Gonzalo Axel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/small_logo.png" />
      </Head>
      <body
        id="body_next"
        
        className="page-template-default page page-id-20830 wp-embed-responsive theme-ohio woocommerce-js ohio-theme-3-1-9 with-switcher with-header-2 with-fixed-search with-headline with-sticky-header with-mobile-switcher links-underline icon-buttons-animation custom-cursor with-ajax-button wpb-js-composer js-comp-ver-6.10.0 vc_responsive elementor-default elementor-kit-216976 page-is-loaded"
        cz-shortcut-listen="true"
      >
       
        <Main />
        <script
          src="https://kit.fontawesome.com/625cb85847.js"
          crossOrigin="anonymous"
        ></script>
        <NextScript />
      </body>
    </Html>
  );
}
