import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>Gonzalo Axel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/small_logo.png" />
      </Head>
      <body>
        
        <Main />
      </body>
      <script
        src="https://kit.fontawesome.com/625cb85847.js"
        crossOrigin="anonymous"
      ></script>
      <NextScript />
    </Html>
  );
}


